export const SEARCH_USER_PROCESSING = "SEARCH_USER_PROCESSING"
export const SEARCH_USER_SUCCESS = "SEARCH_USER_SUCCESS"
export const SEARCH_USER_FAIL = "SEARCH_USER_FAIL"

export const SINGLE_CHAT_CREATE_PROCESSING = "SINGLE_CHAT_CREATE_PROCESSING"
export const SINGLE_CHAT_CREATE_SUCCESS = "SINGLE_CHAT_CREATE_SUCCESS"
export const SINGLE_CHAT_CREATE_FAIL = "SINGLE_CHAT_CREATE_FAIL"
